#!/bin/bash

#SBATCH --job-name=ind-kaidong
#SBATCH --output=job.%j.out
#SBATCH --ntasks=2
#SBATCH --nodes=1
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --constraint="rtx2080"
 
module load singularity || true

sif_path=$HOME/sifs/keras.sif
py_path=/opt/conda/envs/tf2/bin/python3

set -xe

export PYTHONPATH=`pwd`/keras_train
singularity exec --nv $sif_path $py_path keras_train.py
